server:
  port: 7000

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
    #   uri: mongodb://root:generic@localhost:27017/inventorydb
        host: localhost
        port: 27017
        database: requests
        username: root
        password: generic
        authentication-database: admin
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: '*'
            allowedMethods:
            - GET
            - POST
            - DELETE
            - PUT
            
      routes:
        - id: products
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
          filters:
            - RequestFilter

        - id: categories
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/categories/**
          filters:
            - RequestFilter

        - id: hello
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/hello/**
          filters:
            - RequestFilter
        
        - id: orders
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - RequestFilter
        
        - id: inventory
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - RequestFilter
