server:
    port: 6002
spring:
    application:
        name: inventory-service
    data:
        mongodb:
            # url: mongodb://root:generic@localhost:27017/inventory?authSource=admin
            host: localhost
            port: 27017
            database: inventory
            username: root
            password: generic
            authentication-database: admin

eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  

# mongodb://root:generic@localhost:27017/?authSource=admin