server:
    port: 6001
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/order_service
        username: isabel
        password: Seniordev15*
    application:
        name: order-service
    jpa:
        show-sql: true
        hibernate:
         ddl-auto: update