server:
    port: 6001
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/order_service
        username: isabel
        password: Seniordev15*
    application:
        name: order-service
    jpa:
        show-sql: true
        hibernate:
         ddl-auto: update

eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka