server:
   port: 8000

spring:
  # profiles: 
  #   active: development, default
  datasource:
    url: jdbc:mysql://localhost:3306/product_service
    username: isabel
    password: Seniordev15*
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8888


logging:
  # config: classpath:log4j2.properties
  level:
    root: INFO

log4j2:
  enableJndiJdbc: true

